// <auto-generated />
using System;
using FilaZeroApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FilaZeroApi.Migrations
{
    [DbContext(typeof(FilaZeroDBContext))]
    [Migration("20240609224755_mod2")]
    partial class mod2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("FilaZeroApi.models.Agencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("cnpj")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("codigoAgencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("endereco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nomeBanco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nomeCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Agencias");
                });

            modelBuilder.Entity("FilaZeroApi.models.AgenciaCapacidade", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("HorarioAbertura")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HorarioFechamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("agenciaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("lotacao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("quantidadeFichas")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("agenciasCapacidade");
                });
#pragma warning restore 612, 618
        }
    }
}
